// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    CardList: typeof import('./src/components/Homepage/CardList.vue')['default']
    Counter: typeof import('./src/components/Globle/Counter.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Toast: typeof import('./src/components/Globle/Toast.vue')['default']
  }
}

export { }
